dist: focal

jobs:
  include:
    - language: node_js
      node_js:
        - 'lts/*'
      install:
        - npm ci
      script:
        - npm run production
    - language: php
      php:
        - '7.4'
      cache:
        directories:
          - vendor
      install:
        - composer install --no-interaction --no-progress
      before_script:
        - cp .env.example .env
        - php artisan key:generate
      script:
        - vendor/bin/phpcs
        - vendor/bin/phpunit
